/*
 * Copyright (C) 2016-2019 The lgou2w <lgou2w@hotmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.lgou2w.ldk.bukkit.anvil

import com.lgou2w.ldk.asm.ASMClassGenerator
import com.lgou2w.ldk.bukkit.version.MinecraftBukkitVersion
import org.objectweb.asm.ClassWriter
import org.objectweb.asm.Label
import org.objectweb.asm.Opcodes

object AnvilWindowImplGenerator : ASMClassGenerator {

    private val VER = MinecraftBukkitVersion.CURRENT.version

    private fun anvilName(className: String) = "com/lgou2w/ldk/bukkit/anvil/$className"
    private fun anvilDescriptor(className: String) = "L${anvilName(className)};"
    private fun nmsName(className: String) = "net/minecraft/server/$VER/$className"
    private fun nmsDescriptor(className: String) = "L${nmsName(className)};"
    private fun obcName(className: String) = "org/bukkit/craftbukkit/$VER/$className"
    private fun obcDescriptor(className: String) = "L${obcName(className)};"

    override fun generate(): Map<String, ByteArray> {
        val classes = LinkedHashMap<String, ByteArray>(3)
        val anvilWindowImpl = ClassWriter(0x00).apply {
            visit(Opcodes.V1_8, Opcodes.ACC_PUBLIC + Opcodes.ACC_SUPER, anvilName("AnvilWindowImpl"), null, anvilName("AnvilWindowBase"), null)
            visitSource("AnvilWindowImpl.java", null)
            visitField(Opcodes.ACC_PRIVATE, "handle", anvilDescriptor("AnvilWindowImpl\$ContainerImpl"), null, null).visitEnd()
            visitMethod(Opcodes.ACC_PUBLIC, "<init>", "(Lorg/bukkit/plugin/Plugin;)V", null, null).apply {
                visitCode()
                val l0 = Label()
                visitLabel(l0)
                visitLineNumber(21, l0)
                visitVarInsn(Opcodes.ALOAD, 0)
                visitVarInsn(Opcodes.ALOAD, 1)
                visitMethodInsn(Opcodes.INVOKESPECIAL, anvilName("AnvilWindowBase"), "<init>", "(Lorg/bukkit/plugin/Plugin;)V", false)
                val l1 = Label()
                visitLabel(l1)
                visitLineNumber(22, l1)
                visitInsn(Opcodes.RETURN)
                val l2 = Label()
                visitLabel(l2)
                visitLocalVariable("this", anvilDescriptor("AnvilWindowImpl"), null, l0, l2, 0)
                visitLocalVariable("plugin", "Lorg/bukkit/plugin/Plugin;", null, l0, l2, 1)
                visitMaxs(2, 2)
                visitEnd()
            }
            visitMethod(Opcodes.ACC_PUBLIC, "open", "(Lorg/bukkit/entity/Player;)V", null, null).apply {
                visitCode()
                val l0 = Label()
                visitLabel(l0)
                visitLineNumber(26, l0)
                visitVarInsn(Opcodes.ALOAD, 0)
                visitVarInsn(Opcodes.ALOAD, 1)
                visitMethodInsn(Opcodes.INVOKESPECIAL, anvilName("AnvilWindowBase"), "open", "(Lorg/bukkit/entity/Player;)V", false)
                val l1 = Label()
                visitLabel(l1)
                visitLineNumber(27, l1)
                visitVarInsn(Opcodes.ALOAD, 1)
                visitTypeInsn(Opcodes.CHECKCAST, obcName("entity/CraftPlayer"))
                visitMethodInsn(Opcodes.INVOKEVIRTUAL, obcName("entity/CraftPlayer"), "getHandle", "()${nmsDescriptor("EntityPlayer")}", false)
                visitVarInsn(Opcodes.ASTORE, 2)
                val l2 = Label()
                visitLabel(l2)
                visitLineNumber(28, l2)
                visitTypeInsn(Opcodes.NEW, anvilName("AnvilWindowImpl\$TileEntityImpl"))
                visitInsn(Opcodes.DUP)
                visitVarInsn(Opcodes.ALOAD, 0)
                visitVarInsn(Opcodes.ALOAD, 2)
                visitFieldInsn(Opcodes.GETFIELD, nmsName("EntityPlayer"), "world", nmsDescriptor("World"))
                visitMethodInsn(Opcodes.INVOKESPECIAL, anvilName("AnvilWindowImpl\$TileEntityImpl"), "<init>", "(${anvilDescriptor("AnvilWindowImpl")}${nmsDescriptor("World")})V", false)
                visitVarInsn(Opcodes.ASTORE, 3)
                val l3 = Label()
                visitLabel(l3)
                visitLineNumber(29, l3)
                visitVarInsn(Opcodes.ALOAD, 2)
                visitVarInsn(Opcodes.ALOAD, 3)
                visitMethodInsn(Opcodes.INVOKEVIRTUAL, nmsName("EntityPlayer"), "openTileEntity", "(${nmsDescriptor("ITileEntityContainer")})V", false)
                val l4 = Label()
                visitLabel(l4)
                visitLineNumber(30, l4)
                visitInsn(Opcodes.RETURN)
                val l5 = Label()
                visitLabel(l5)
                visitLocalVariable("this", anvilDescriptor("AnvilWindowImpl"), null, l0, l5, 0)
                visitLocalVariable("player", "Lorg/bukkit/entity/Player;", null, l0, l5, 1)
                visitLocalVariable("playerHandle", nmsDescriptor("EntityPlayer"), null, l2, l5, 2)
                visitLocalVariable("tileEntity", anvilDescriptor("AnvilWindowImpl\$TileEntityImpl"), null, l3, l5, 3)
                visitMaxs(4, 4)
                visitEnd()
            }
            visitMethod(Opcodes.ACC_PROTECTED, "getHandle", "()Ljava/lang/Object;", null, null).apply {
                visitCode()
                val l0 = Label()
                visitLabel(l0)
                visitLineNumber(34, l0)
                visitVarInsn(Opcodes.ALOAD, 0)
                visitFieldInsn(Opcodes.GETFIELD, anvilName("AnvilWindowImpl"), "handle", anvilDescriptor("AnvilWindowImpl\$ContainerImpl"))
                visitInsn(Opcodes.ARETURN)
                val l1 = Label()
                visitLabel(l1)
                visitLocalVariable("this", anvilDescriptor("AnvilWindowImpl"), null, l0, l1, 0)
                visitMaxs(1, 1)
                visitEnd()
            }
            visitMethod(Opcodes.ACC_PROTECTED, "setHandle", "(Ljava/lang/Object;)V", null, null).apply {
                visitCode()
                val l0 = Label()
                visitLabel(l0)
                visitLineNumber(39, l0)
                visitVarInsn(Opcodes.ALOAD, 0)
                visitVarInsn(Opcodes.ALOAD, 1)
                visitTypeInsn(Opcodes.CHECKCAST, anvilName("AnvilWindowImpl\$ContainerImpl"))
                visitFieldInsn(Opcodes.PUTFIELD, anvilName("AnvilWindowImpl"), "handle", anvilDescriptor("AnvilWindowImpl\$ContainerImpl"))
                val l1 = Label()
                visitLabel(l1)
                visitLineNumber(40, l1)
                visitInsn(Opcodes.RETURN)
                val l2 = Label()
                visitLabel(l2)
                visitLocalVariable("this", anvilDescriptor("AnvilWindowImpl"), null, l0, l2, 0)
                visitLocalVariable("handle", "Ljava/lang/Object;", null, l0, l2, 1)
                visitMaxs(2, 2)
                visitEnd()
            }
            visitMethod(Opcodes.ACC_PROTECTED, "getInventory", "()Lorg/bukkit/inventory/Inventory;", null, null).apply {
                visitCode()
                val l0 = Label()
                visitLabel(l0)
                visitLineNumber(44, l0)
                visitVarInsn(Opcodes.ALOAD, 0)
                visitFieldInsn(Opcodes.GETFIELD, anvilName("AnvilWindowImpl"), "handle", anvilDescriptor("AnvilWindowImpl\$ContainerImpl"))
                visitMethodInsn(Opcodes.INVOKEVIRTUAL, anvilName("AnvilWindowImpl\$ContainerImpl"), "getBukkitView", "()${obcDescriptor("inventory/CraftInventoryView")}", false)
                visitMethodInsn(Opcodes.INVOKEVIRTUAL, obcDescriptor("inventory/CraftInventoryView"), "getTopInventory", "()Lorg/bukkit/inventory/Inventory;", false)
                visitInsn(Opcodes.ARETURN)
                val l1 = Label()
                visitLabel(l1)
                visitLocalVariable("this", anvilDescriptor("AnvilWindowImpl"), null, l0, l1, 0)
                visitMaxs(1, 1)
                visitEnd()
            }
            visitInnerClass(anvilName("AnvilWindowImpl\$ContainerImpl"), "AnvilWindowImpl", "ContainerImpl", Opcodes.ACC_PUBLIC)
            visitInnerClass(anvilName("AnvilWindowImpl\$TileEntityImpl"), "AnvilWindowImpl", "TileEntityImpl", Opcodes.ACC_PUBLIC)
        }.toByteArray()
        val anvilWindowImplTileEntityImpl = ClassWriter(0x00).apply {
            visit(Opcodes.V1_8, Opcodes.ACC_SUPER, anvilName("AnvilWindowImpl\$TileEntityImpl"), null, nmsName("BlockAnvil\$TileEntityContainerAnvil"), null)
            visitSource("AnvilWindowImpl.java", null)
            visitField(Opcodes.ACC_PRIVATE + Opcodes.ACC_FINAL, "anvilWindow", anvilDescriptor("AnvilWindowImpl"), null, null)
            visitMethod(0x00, "<init>", "(${anvilDescriptor("AnvilWindowImpl")}${nmsDescriptor("World")})V", null, null).apply {
                visitCode()
                val l0 = Label()
                visitLabel(l0)
                visitLineNumber(51, l0)
                visitVarInsn(Opcodes.ALOAD, 0)
                visitVarInsn(Opcodes.ALOAD, 2)
                visitFieldInsn(Opcodes.GETSTATIC, nmsName("BlockPosition"), "ZERO", nmsDescriptor("BlockPosition"))
                visitMethodInsn(Opcodes.INVOKESPECIAL, nmsName("BlockAnvil\$TileEntityContainerAnvil"), "<init>", "(${nmsDescriptor("World")}${nmsDescriptor("BlockPosition")})V", false)
                val l1 = Label()
                visitLabel(l1)
                visitLineNumber(52, l1)
                visitVarInsn(Opcodes.ALOAD, 0)
                visitVarInsn(Opcodes.ALOAD, 1)
                visitFieldInsn(Opcodes.PUTFIELD, anvilName("AnvilWindowImpl\$TileEntityImpl"), "anvilWindow", anvilDescriptor("AnvilWindowImpl"))
                val l2 = Label()
                visitLabel(l2)
                visitLineNumber(53, l2)
                visitInsn(Opcodes.RETURN)
                val l3 = Label()
                visitLabel(l3)
                visitLocalVariable("this", anvilDescriptor("AnvilWindowImpl\$TileEntityImpl"), null, l0, l3, 0)
                visitLocalVariable("anvilWindow", anvilDescriptor("AnvilWindowImpl"), null, l0, l3, 1)
                visitLocalVariable("world", nmsDescriptor("World"), null, l0, l3, 2)
                visitMaxs(3, 3)
                visitEnd()
            }
            visitMethod(Opcodes.ACC_PUBLIC, "createContainer", "(${nmsDescriptor("PlayerInventory")}${nmsDescriptor("EntityHuman")})${nmsDescriptor("Container")}", null, null).apply {
                visitCode()
                val l0 = Label()
                visitLabel(l0)
                visitLineNumber(58, l0)
                visitTypeInsn(Opcodes.NEW, anvilName("AnvilWindowImpl\$ContainerImpl"))
                visitInsn(Opcodes.DUP)
                visitVarInsn(Opcodes.ALOAD, 0)
                visitFieldInsn(Opcodes.GETFIELD, anvilName("AnvilWindowImpl\$TileEntityImpl"), "anvilWindow", anvilDescriptor("AnvilWindowImpl"))
                visitVarInsn(Opcodes.ALOAD, 1)
                visitVarInsn(Opcodes.ALOAD, 2)
                visitMethodInsn(Opcodes.INVOKESPECIAL, anvilName("AnvilWindowImpl\$ContainerImpl"), "<init>", "(${anvilDescriptor("AnvilWindowImpl")}${nmsDescriptor("PlayerInventory")}${nmsDescriptor("EntityHuman")})V", false)
                visitVarInsn(Opcodes.ASTORE, 3)
                val l1 = Label()
                visitLabel(l1)
                visitLineNumber(59, l1)
                visitVarInsn(Opcodes.ALOAD, 0)
                visitFieldInsn(Opcodes.GETFIELD, anvilName("AnvilWindowImpl\$TileEntityImpl"), "anvilWindow", anvilDescriptor("AnvilWindowImpl"))
                visitVarInsn(Opcodes.ALOAD, 3)
                visitMethodInsn(Opcodes.INVOKEVIRTUAL, anvilName("AnvilWindowImpl"), "setHandle", "(Ljava/lang/Object;)V", false)
                val l2 = Label()
                visitLabel(l2)
                visitLineNumber(60, l2)
                visitVarInsn(Opcodes.ALOAD, 0)
                visitFieldInsn(Opcodes.GETFIELD, anvilName("AnvilWindowImpl\$TileEntityImpl"), "anvilWindow", anvilDescriptor("AnvilWindowImpl"))
                visitMethodInsn(Opcodes.INVOKEVIRTUAL, anvilName("AnvilWindowImpl"), "callOpenedEvent", "()${anvilDescriptor("AnvilWindowOpenEvent")}", false)
                visitInsn(Opcodes.POP)
                val l3 = Label()
                visitLabel(l3)
                visitLineNumber(61, l3)
                visitVarInsn(Opcodes.ALOAD, 3)
                visitInsn(Opcodes.ARETURN)
                val l4 = Label()
                visitLabel(l4)
                visitLocalVariable("this", anvilDescriptor("AnvilWindowImpl\$TileEntityImpl"), null, l0, l4, 0)
                visitLocalVariable("inventory", nmsDescriptor("PlayerInventory"), null, l0, l4, 1)
                visitLocalVariable("human", nmsDescriptor("EntityHuman"), null, l0, l4, 2)
                visitLocalVariable("container", anvilDescriptor("AnvilWindowImpl\$ContainerImpl"), null, l1, l4, 3)
                visitMaxs(5, 4)
                visitEnd()
            }
            visitInnerClass(anvilName("AnvilWindowImpl\$TileEntityImpl"), "AnvilWindowImpl", "TileEntityImpl", Opcodes.ACC_PUBLIC)
            visitInnerClass(anvilName("AnvilWindowImpl\$ContainerImpl"), "AnvilWindowImpl", "ContainerImpl", Opcodes.ACC_PUBLIC)
            visitInnerClass(nmsName("BlockAnvil\$TileEntityContainerAnvil"), "BlockAnvil", "TileEntityContainerAnvil", Opcodes.ACC_PUBLIC + Opcodes.ACC_STATIC)
        }.toByteArray()
        val anvilWindowImplContainerImpl = ClassWriter(0x00).apply {
            visit(Opcodes.V1_8, Opcodes.ACC_SUPER, anvilName("AnvilWindowImpl\$ContainerImpl"), null, nmsName("ContainerAnvil"), null)
            visitSource("AnvilWindowImpl.java", null)
            visitField(Opcodes.ACC_PRIVATE + Opcodes.ACC_FINAL, "anvilWindow", anvilDescriptor("AnvilWindowImpl"), null, null)
            visitMethod(0x00, "<init>", "(${anvilDescriptor("AnvilWindowImpl")}${nmsDescriptor("PlayerInventory")}${nmsDescriptor("EntityHuman")})V", null, null).apply {
                visitCode()
                val l0 = Label()
                visitLabel(l0)
                visitLineNumber(69, l0)
                visitVarInsn(Opcodes.ALOAD, 0)
                visitVarInsn(Opcodes.ALOAD, 2)
                visitVarInsn(Opcodes.ALOAD, 3)
                visitFieldInsn(Opcodes.GETFIELD, nmsName("EntityHuman"), "world", nmsDescriptor("World"))
                visitFieldInsn(Opcodes.GETSTATIC, nmsName("BlockPosition"), "ZERO", nmsDescriptor("BlockPosition"))
                visitVarInsn(Opcodes.ALOAD, 3)
                visitMethodInsn(Opcodes.INVOKESPECIAL, nmsName("ContainerAnvil"), "<init>", "(${nmsDescriptor("PlayerInventory")}${nmsDescriptor("World")}${nmsDescriptor("BlockPosition")}${nmsDescriptor("EntityHuman")})V", false)
                val l1 = Label()
                visitLabel(l1)
                visitLineNumber(70, l1)
                visitVarInsn(Opcodes.ALOAD, 0)
                visitVarInsn(Opcodes.ALOAD, 1)
                visitFieldInsn(Opcodes.PUTFIELD, anvilName("AnvilWindowImpl\$ContainerImpl"), "anvilWindow", anvilDescriptor("AnvilWindowImpl"))
                val l2 = Label()
                visitLabel(l2)
                visitLineNumber(71, l2)
                visitInsn(Opcodes.RETURN)
                val l3 = Label()
                visitLabel(l3)
                visitLocalVariable("this", anvilDescriptor("AnvilWindowImpl\$ContainerImpl"), null, l0, l3, 0)
                visitLocalVariable("anvilWindow", anvilDescriptor("AnvilWindowImpl"), null, l0, l3, 1)
                visitLocalVariable("inventory", nmsDescriptor("PlayerInventory"), null, l0, l3, 2)
                visitLocalVariable("human", nmsDescriptor("EntityHuman"), null, l0, l3, 3)
                visitMaxs(5, 4)
                visitEnd()
            }
            visitMethod(Opcodes.ACC_PUBLIC, "getAnvilWindow", "()${anvilDescriptor("AnvilWindowBase")}", null, null).apply {
                visitCode()
                val l0 = Label()
                visitLabel(l0)
                visitLineNumber(75, l0)
                visitVarInsn(Opcodes.ALOAD, 0)
                visitFieldInsn(Opcodes.GETFIELD, anvilName("AnvilWindowImpl\$ContainerImpl"), "anvilWindow", anvilDescriptor("AnvilWindowImpl"))
                visitInsn(Opcodes.ARETURN)
                val l1 = Label()
                visitLabel(l1)
                visitLocalVariable("this", anvilDescriptor("AnvilWindowImpl\$ContainerImpl"), null, l0, l1, 0)
                visitMaxs(1, 1)
                visitEnd()
            }
            visitMethod(Opcodes.ACC_PUBLIC, "canUse", "(${nmsDescriptor("EntityHuman")})Z", null, null).apply {
                visitCode()
                val l0 = Label()
                visitLabel(l0)
                visitLineNumber(80, l0)
                visitInsn(Opcodes.ICONST_1)
                visitInsn(Opcodes.IRETURN)
                val l1 = Label()
                visitLabel(l1)
                visitLocalVariable("this", anvilDescriptor("AnvilWindowImpl\$ContainerImpl"), null, l0, l1, 0)
                visitLocalVariable("human", nmsDescriptor("EntityHuman"), null, l0, l1, 1)
                visitMaxs(1, 2)
                visitEnd()
            }
            visitMethod(Opcodes.ACC_PUBLIC, "a", "(Ljava/lang/String;)V", null, null).apply {
                visitCode()
                val l0 = Label()
                visitLabel(l0)
                visitLineNumber(85, l0)
                visitVarInsn(Opcodes.ALOAD, 0)
                visitFieldInsn(Opcodes.GETFIELD, anvilName("AnvilWindowImpl\$ContainerImpl"), "anvilWindow", anvilDescriptor("AnvilWindowImpl"))
                visitVarInsn(Opcodes.ALOAD, 1)
                visitMethodInsn(Opcodes.INVOKEVIRTUAL, anvilName("AnvilWindowImpl"), "callInputtedEvent", "(Ljava/lang/String;)${anvilDescriptor("AnvilWindowInputEvent")}", false)
                visitVarInsn(Opcodes.ASTORE, 2)
                val l1 = Label()
                visitLabel(l1)
                visitLineNumber(86, l1)
                visitVarInsn(Opcodes.ALOAD, 2)
                val l3 = Label()
                visitJumpInsn(Opcodes.IFNONNULL, l3)
                val l2 = Label()
                visitLabel(l2)
                visitLineNumber(87, l2)
                visitVarInsn(Opcodes.ALOAD, 0)
                visitVarInsn(Opcodes.ALOAD, 1)
                visitMethodInsn(Opcodes.INVOKESPECIAL, nmsName("ContainerAnvil"), "a", "(Ljava/lang/String;)V", false)
                val l5 = Label()
                visitJumpInsn(Opcodes.GOTO, l5)
                visitLabel(l3)
                visitLineNumber(88, l3)
                visitFrame(Opcodes.F_APPEND, 1, arrayOf(anvilName("AnvilWindowInputEvent")), 0, null)
                visitVarInsn(Opcodes.ALOAD, 2)
                visitMethodInsn(Opcodes.INVOKEVIRTUAL, anvilName("AnvilWindowInputEvent"), "isCancelled", "()Z", false)
                visitJumpInsn(Opcodes.IFNE, l5)
                val l4 = Label()
                visitLabel(l4)
                visitLineNumber(89, l4)
                visitVarInsn(Opcodes.ALOAD, 0)
                visitVarInsn(Opcodes.ALOAD, 2)
                visitMethodInsn(Opcodes.INVOKEVIRTUAL, anvilName("AnvilWindowInputEvent"), "getValue", "()Ljava/lang/String;", false)
                visitMethodInsn(Opcodes.INVOKESPECIAL, nmsName("ContainerAnvil"), "a", "(Ljava/lang/String;)V", false)
                visitLabel(l5)
                visitLineNumber(90, l5)
                visitFrame(Opcodes.F_SAME, 0, null, 0, null)
                visitInsn(Opcodes.RETURN)
                val l6 = Label()
                visitLabel(l6)
                visitLocalVariable("this", anvilDescriptor("AnvilWindowImpl\$ContainerImpl"), null, l0, l6, 0)
                visitLocalVariable("value", "Ljava/lang/String;", null, l0, l6, 1)
                visitLocalVariable("event", anvilDescriptor("AnvilWindowInputEvent"), null, l1, l6, 2)
                visitMaxs(2, 3)
                visitEnd()
            }
            visitMethod(Opcodes.ACC_PUBLIC, "b", "(${nmsDescriptor("EntityHuman")})V", null, null).apply {
                visitCode()
                val l0 = Label()
                visitLabel(l0)
                visitLineNumber(94, l0)
                visitVarInsn(Opcodes.ALOAD, 0)
                visitFieldInsn(Opcodes.GETFIELD, anvilName("AnvilWindowImpl\$ContainerImpl"), "anvilWindow", anvilDescriptor("AnvilWindowImpl"))
                visitMethodInsn(Opcodes.INVOKEVIRTUAL, anvilName("AnvilWindowImpl"), "callClosedEvent", "()${anvilDescriptor("AnvilWindowCloseEvent")}", false)
                visitInsn(Opcodes.POP)
                val l1 = Label()
                visitLabel(l1)
                visitLineNumber(95, l1)
                visitVarInsn(Opcodes.ALOAD, 0)
                visitFieldInsn(Opcodes.GETFIELD, anvilName("AnvilWindowImpl\$ContainerImpl"), "anvilWindow", anvilDescriptor("AnvilWindowImpl"))
                visitMethodInsn(Opcodes.INVOKEVIRTUAL, anvilName("AnvilWindowImpl"), "release", "()V", false)
                val l2 = Label()
                visitLabel(l2)
                visitLineNumber(96, l2)
                visitVarInsn(Opcodes.ALOAD, 0)
                visitVarInsn(Opcodes.ALOAD, 1)
                visitMethodInsn(Opcodes.INVOKESPECIAL, nmsName("ContainerAnvil"), "b", "(${nmsDescriptor("EntityHuman")})V", false)
                val l3 = Label()
                visitLabel(l3)
                visitLineNumber(97, l3)
                visitInsn(Opcodes.RETURN)
                val l4 = Label()
                visitLabel(l4)
                visitLocalVariable("this", anvilDescriptor("AnvilWindowImpl\$ContainerImpl"), null, l0, l4, 0)
                visitLocalVariable("human", nmsDescriptor("EntityHuman"), null, l0, l4, 1)
                visitMaxs(2, 2)
                visitEnd()
            }
            visitInnerClass(anvilName("AnvilWindowImpl\$ContainerImpl"), "AnvilWindowImpl", "ContainerImpl", Opcodes.ACC_PUBLIC)
        }.toByteArray()
        classes["com.lgou2w.ldk.bukkit.anvil.AnvilWindowImpl\$ContainerImpl"] = anvilWindowImplContainerImpl
        classes["com.lgou2w.ldk.bukkit.anvil.AnvilWindowImpl\$TileEntityImpl"] = anvilWindowImplTileEntityImpl
        classes["com.lgou2w.ldk.bukkit.anvil.AnvilWindowImpl"] = anvilWindowImpl
        return classes
    }
}
