/*
 * The MIT License (MIT)
 *
 * Copyright (c) 2018 Hex_27
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included
 * in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

/*
 * Copyright (C) 2018 25 (https://github.com/25)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * Copyright (C) 2018 The lgou2w <lgou2w@hotmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.lgou2w.ldk.bukkit.compatibility

import com.lgou2w.ldk.bukkit.version.Draft
import com.lgou2w.ldk.bukkit.version.MinecraftBukkitVersion
import com.lgou2w.ldk.common.notNull
import org.bukkit.Bukkit
import org.bukkit.Material
import org.bukkit.inventory.ItemStack
import java.util.Collections
import java.util.Locale

/**
 * ## XMaterial (材料)
 *
 * @see [Material]
 * @author Hex_27, 25, lgou2w
 */
enum class XMaterial {

    //<editor-fold desc="XMaterials" defaultstate="collapsed">

    ACACIA_BOAT("BOAT_ACACIA", 0),
    ACACIA_BUTTON("WOOD_BUTTON", 0),
    ACACIA_DOOR(0, "ACACIA_DOOR", "ACACIA_DOOR_ITEM"),
    ACACIA_FENCE("ACACIA_FENCE", 0),
    ACACIA_FENCE_GATE("ACACIA_FENCE_GATE", 0),
    ACACIA_LEAVES("LEAVES_2", 0),
    ACACIA_LOG("LOG_2", 0),
    ACACIA_PLANKS("WOOD", 4),
    ACACIA_PRESSURE_PLATE("WOOD_PLATE", 0),
    ACACIA_SAPLING("SAPLING", 4),
    ACACIA_SLAB(4, "WOODEN_SLAB", "WOOD_STEP", "WOOD_DOUBLE_STEP"),
    ACACIA_STAIRS("ACACIA_STAIRS", 4),
    ACACIA_TRAPDOOR("TRAP_DOOR", 0),
    ACACIA_WOOD("LOG_2", 0),
    ACTIVATOR_RAIL("ACTIVATOR_RAIL", 0),
    AIR("AIR", 0),
    ALLIUM("STONE", 0),
    ANDESITE("STONE", 5),
    ANVIL("ANVIL", 0),
    APPLE("APPLE", 0),
    ARMOR_STAND("ARMOR_STAND", 0),
    ARROW("ARROW", 0),
    ATTACHED_MELON_STEM("MELON_STEM", 7),
    ATTACHED_PUMPKIN_STEM("PUMPKIN_STEM", 7),
    AZURE_BLUET("RED_ROSE", 3),
    BAKED_POTATO("BAKED_POTATO", 0),
    BARRIER("BARRIER", 0),
    BAT_SPAWN_EGG("MONSTER_EGG", 0),
    BEACON("BEACON", 0),
    BEDROCK("BEDROCK", 0),
    BEEF("RAW_BEEF", 0),
    BEETROOT("BEETROOT", 0),
    BEETROOTS(0, "BEETROOT", "BEETROOT_BLOCK"),
    BEETROOT_SEEDS("BEETROOT_SEEDS", 0),
    BEETROOT_SOUP("BEETROOT_SOUP", 0),
    BIRCH_BOAT("BOAT_BIRCH", 0),
    BIRCH_BUTTON("WOOD_BUTTON", 0),
    BIRCH_DOOR(0, "BIRCH_DOOR", "BIRCH_DOOR_ITEM"),
    BIRCH_FENCE("BIRCH_FENCE", 0),
    BIRCH_FENCE_GATE("BIRCH_FENCE_GATE", 0),
    BIRCH_LEAVES("LEAVES", 2),
    BIRCH_LOG("LOG", 2),
    BIRCH_PLANKS("WOOD", 2),
    BIRCH_PRESSURE_PLATE("WOOD_PLATE", 0),
    BIRCH_SAPLING("SAPLING", 2),
    BIRCH_SLAB(2, "WOODEN_SLAB", "WOOD_STEP", "WOOD_DOUBLE_STEP"),
    BIRCH_STAIRS("BIRCH_WOOD_STAIRS", 0),
    BIRCH_TRAPDOOR("TRAP_DOOR", 0),
    BIRCH_WOOD("LOG", 2),
    BLACK_BANNER(0, "BANNER", "STANDING_BANNER"),
    BLACK_BED("BED", 15),
    BLACK_CARPET("CARPET", 15),
    BLACK_CONCRETE("CONCRETE", 15),
    BLACK_CONCRETE_POWDER("CONCRETE_POWDER", 15),
    BLACK_GLAZED_TERRACOTTA("BLACK_GLAZED_TERRACOTTA", 0),
    BLACK_SHULKER_BOX("BLACK_SHULKER_BOX", 0),
    BLACK_STAINED_GLASS("STAINED_GLASS", 15),
    BLACK_STAINED_GLASS_PANE("STAINED_GLASS_PANE", 15),
    BLACK_TERRACOTTA("STAINED_CLAY", 15),
    BLACK_WALL_BANNER("WALL_BANNER", 0),
    BLACK_WOOL("WOOL", 15),
    BLAZE_POWDER("BLAZE_POWDER", 0),
    BLAZE_ROD("BLAZE_ROD", 0),
    BLAZE_SPAWN_EGG("MONSTER_EGG", 0),
    BLUE_BANNER(11, "BANNER", "STANDING_BANNER"),
    BLUE_BED("BED", 4),
    BLUE_CARPET("CARPET", 11),
    BLUE_CONCRETE("CONCRETE", 11),
    BLUE_CONCRETE_POWDER("CONCRETE_POWDER", 11),
    BLUE_GLAZED_TERRACOTTA("BLUE_GLAZED_TERRACOTTA", 0),
    BLUE_ICE("PACKED_ICE", 0),
    BLUE_ORCHID("RED_ROSE", 1),
    BLUE_SHULKER_BOX("BLUE_SHULKER_BOX", 0),
    BLUE_STAINED_GLASS("STAINED_GLASS", 11),
    BLUE_STAINED_GLASS_PANE("STAINED_GLASS_PANE", 11),
    BLUE_TERRACOTTA("STAINED_CLAY", 11),
    BLUE_WALL_BANNER("WALL_BANNER", 11),
    BLUE_WOOL("WOOL", 11),
    BONE("BONE", 0),
    BONE_BLOCK("BONE_BLOCK", 0),
    BONE_MEAL("INK_SACK", 15),
    BOOK("BOOK", 0),
    BOOKSHELF("BOOKSHELF", 0),
    BOW("BOW", 0),
    BOWL("BOWL", 0),
    BRAIN_CORAL("STONE", 0),
    BRAIN_CORAL_BLOCK("STONE", 0),
    BRAIN_CORAL_FAN("STONE", 0),
    BRAIN_CORAL_WALL_FAN("STONE", 0),
    BREAD("BREAD", 0),
    BREWING_STAND(0, "BREWING_STAND", "BREWING_STAND_ITEM"),
    BRICK("CLAY_BRICK", 0),
    BRICKS("BRICK", 0),
    BRICK_SLAB(4, "STONE_SLAB", "STEP", "DOUBLE_STEP"),
    BRICK_STAIRS("BRICK_STAIRS", 0),
    BROWN_BANNER(3, "BANNER", "STANDING_BANNER"),
    BROWN_BED("BED", 12),
    BROWN_CARPET("CARPET", 12),
    BROWN_CONCRETE("CONCRETE", 12),
    BROWN_CONCRETE_POWDER("CONCRETE_POWDER", 12),
    BROWN_GLAZED_TERRACOTTA("BROWN_GLAZED_TERRACOTTA", 0),
    BROWN_MUSHROOM("BROWN_MUSHROOM", 0),
    BROWN_MUSHROOM_BLOCK(0, "BROWN_MUSHROOM", "HUGE_MUSHROOM_1"),
    BROWN_SHULKER_BOX("BROWN_SHULKER_BOX", 0),
    BROWN_STAINED_GLASS("STAINED_GLASS", 12),
    BROWN_STAINED_GLASS_PANE("STAINED_GLASS_PANE", 12),
    BROWN_TERRACOTTA("STAINED_CLAY", 12),
    BROWN_WALL_BANNER("WALL_BANNER", 3),
    BROWN_WOOL("WOOL", 12),
    BUBBLE_COLUMN("STONE", 0),
    BUBBLE_CORAL("STONE", 0),
    BUBBLE_CORAL_BLOCK("STONE", 0),
    BUBBLE_CORAL_FAN("STONE", 0),
    BUBBLE_CORAL_WALL_FAN("STONE", 0),
    BUCKET("BUCKET", 0),
    CACTUS("CACTUS", 0),
    CACTUS_GREEN("INK_SACK", 2),
    CAKE(0, "CAKE", "CAKE_BLOCK"),
    CARROT("CARROT_ITEM", 0),
    CARROTS("CARROT", 0),
    CARROT_ON_A_STICK("CARROT_STICK", 0),
    CARVED_PUMPKIN("PUMPKIN", 0),
    CAULDRON(0, "CAULDRON", "CAULDRON_ITEM"),
    CAVE_AIR("AIR", 0),
    CAVE_SPIDER_SPAWN_EGG("MONSTER_EGG", 0),
    CHAINMAIL_BOOTS("CHAINMAIL_BOOTS", 0),
    CHAINMAIL_CHESTPLATE("CHAINMAIL_CHESTPLATE", 0),
    CHAINMAIL_HELMET("CHAINMAIL_HELMET", 0),
    CHAINMAIL_LEGGINGS("CHAINMAIL_LEGGINGS", 0),
    CHAIN_COMMAND_BLOCK("COMMAND_CHAIN", 0),
    CHARCOAL("COAL", 1),
    CHEST(0, "CHEST", "LOCKED_CHEST"),
    CHEST_MINECART("STORAGE_MINECART", 0),
    CHICKEN("RAW_CHICKEN", 0),
    CHICKEN_SPAWN_EGG("MONSTER_EGG", 0),
    CHIPPED_ANVIL("ANVIL", 1),
    CHISELED_QUARTZ_BLOCK("QUARTZ_BLOCK", 1),
    CHISELED_RED_SANDSTONE("RED_SANDSTONE", 1),
    CHISELED_SANDSTONE("SANDSTONE", 1),
    CHISELED_STONE_BRICKS("SMOOTH_BRICK", 3),
    CHORUS_FLOWER("CHORUS_FLOWER", 0),
    CHORUS_FRUIT("CHORUS_FRUIT", 0),
    CHORUS_PLANT("CHORUS_PLANT", 0),
    CLAY("CLAY", 0),
    CLAY_BALL("CLAY_BALL", 0),
    CLOCK("WATCH", 0),
    COAL("COAL", 0),
    COAL_BLOCK("COAL_BLOCK", 0),
    COAL_ORE("COAL_ORE", 0),
    COARSE_DIRT("DIRT", 1),
    COBBLESTONE("COBBLESTONE", 0),
    COBBLESTONE_SLAB(3, "STONE_SLAB", "STEP", "DOUBLE_STEP"),
    COBBLESTONE_STAIRS("COBBLESTONE_STAIRS", 0),
    COBBLESTONE_WALL("COBBLE_WALL", 0),
    COBWEB("WEB", 0),
    COCOA("COCOA", 0),
    COCOA_BEANS("INK_SACK", 3),
    COD("RAW_FISH", 0),
    COD_BUCKET("BUCKET", 0),
    COD_SPAWN_EGG("MONSTER_EGG", 0),
    COMMAND_BLOCK("COMMAND", 0),
    COMMAND_BLOCK_MINECART("COMMAND_MINECART", 0),
    COMPARATOR(0, "REDSTONE_COMPARATOR", "REDSTONE_COMPARATOR_ON", "REDSTONE_COMPARATOR_OFF"),
    COMPASS("COMPASS", 0),
    CONDUIT("STONE", 0),
    COOKED_BEEF("COOKED_BEEF", 0),
    COOKED_CHICKEN("COOKED_CHICKEN", 0),
    COOKED_COD("COOKED_FISH", 0),
    COOKED_MUTTON("COOKED_MUTTON", 0),
    COOKED_PORKCHOP("GRILLED_PORK", 0),
    COOKED_RABBIT("COOKED_RABBIT", 0),
    COOKED_SALMON("COOKED_FISH", 1),
    COOKIE("COOKIE", 0),
    COW_SPAWN_EGG("MONSTER_EGG", 0),
    CRACKED_STONE_BRICKS("SMOOTH_BRICK", 2),
    CRAFTING_TABLE("WORKBENCH", 0),
    CREEPER_HEAD(4, "SKULL", "SKULL_ITEM"),
    CREEPER_SPAWN_EGG("MONSTER_EGG", 0),
    CREEPER_WALL_HEAD("SKULL", 4),
    CUT_RED_SANDSTONE("STONE", 0),
    CUT_SANDSTONE("STONE", 0),
    CYAN_BANNER(6, "BANNER", "STANDING_BANNER"),
    CYAN_BED("BED", 9),
    CYAN_CARPET("CARPET", 9),
    CYAN_CONCRETE("CONCRETE", 9),
    CYAN_CONCRETE_POWDER("CONCRETE_POWDER", 9),
    CYAN_DYE("INK_SACK", 6),
    CYAN_GLAZED_TERRACOTTA("CYAN_GLAZED_TERRACOTTA", 0),
    CYAN_SHULKER_BOX("CYAN_SHULKER_BOX", 0),
    CYAN_STAINED_GLASS("STAINED_GLASS", 9),
    CYAN_STAINED_GLASS_PANE("STAINED_GLASS_PANE", 9),
    CYAN_TERRACOTTA("STAINED_CLAY", 9),
    CYAN_WALL_BANNER("WALL_BANNER", 0),
    CYAN_WOOL("WOOL", 9),
    DAMAGED_ANVIL("ANVIL", 2),
    DANDELION("YELLOW_FLOWER", 0),
    DANDELION_YELLOW("INK_SACK", 11),
    DARK_OAK_BOAT("BOAT_DARK_OAK", 0),
    DARK_OAK_BUTTON("WOOD_BUTTON", 0),
    DARK_OAK_DOOR(0, "DARK_OAK_DOOR", "DARK_OAK_DOOR_ITEM"),
    DARK_OAK_FENCE("DARK_OAK_FENCE", 0),
    DARK_OAK_FENCE_GATE("DARK_OAK_FENCE_GATE", 0),
    DARK_OAK_LEAVES("LEAVES_2", 1),
    DARK_OAK_LOG("LOG_2", 1),
    DARK_OAK_PLANKS("WOOD", 5),
    DARK_OAK_PRESSURE_PLATE("WOOD_PLATE", 0),
    DARK_OAK_SAPLING("SAPLING", 5),
    DARK_OAK_SLAB(5, "WOODEN_SLAB", "WOOD_STEP", "WOOD_DOUBLE_STEP"),
    DARK_OAK_STAIRS("DARK_OAK_STAIRS", 0),
    DARK_OAK_TRAPDOOR("TRAP_DOOR", 0),
    DARK_OAK_WOOD("LOG_2", 1),
    DARK_PRISMARINE("PRISMARINE", 2),
    DARK_PRISMARINE_SLAB("STONE", 0),
    DARK_PRISMARINE_STAIRS("STONE", 0),
    DAYLIGHT_DETECTOR(0, "DAYLIGHT_DETECTOR", "DAYLIGHT_DETECTOR_INVERTED"),
    DEAD_BRAIN_CORAL("STONE", 0),
    DEAD_BRAIN_CORAL_BLOCK("STONE", 0),
    DEAD_BRAIN_CORAL_FAN("STONE", 0),
    DEAD_BRAIN_CORAL_WALL_FAN("STONE", 0),
    DEAD_BUBBLE_CORAL("STONE", 0),
    DEAD_BUBBLE_CORAL_BLOCK("STONE", 0),
    DEAD_BUBBLE_CORAL_FAN("STONE", 0),
    DEAD_BUBBLE_CORAL_WALL_FAN("STONE", 0),
    DEAD_BUSH("DEAD_BUSH", 0),
    DEAD_FIRE_CORAL("STONE", 0),
    DEAD_FIRE_CORAL_BLOCK("STONE", 0),
    DEAD_FIRE_CORAL_FAN("STONE", 0),
    DEAD_FIRE_CORAL_WALL_FAN("STONE", 0),
    DEAD_HORN_CORAL("STONE", 0),
    DEAD_HORN_CORAL_BLOCK("STONE", 0),
    DEAD_HORN_CORAL_FAN("STONE", 0),
    DEAD_HORN_CORAL_WALL_FAN("STONE", 0),
    DEAD_TUBE_CORAL("STONE", 0),
    DEAD_TUBE_CORAL_BLOCK("STONE", 0),
    DEAD_TUBE_CORAL_FAN("STONE", 0),
    DEAD_TUBE_CORAL_WALL_FAN("STONE", 0),
    DEBUG_STICK("STICK", 0),
    DETECTOR_RAIL("DETECTOR_RAIL", 0),
    DIAMOND("DIAMOND", 0),
    DIAMOND_AXE("DIAMOND_AXE", 0),
    DIAMOND_BLOCK("DIAMOND_BLOCK", 0),
    DIAMOND_BOOTS("DIAMOND_BOOTS", 0),
    DIAMOND_CHESTPLATE("DIAMOND_CHESTPLATE", 0),
    DIAMOND_HELMET("DIAMOND_HELMET", 0),
    DIAMOND_HOE("DIAMOND_HOE", 0),
    DIAMOND_HORSE_ARMOR("DIAMOND_BARDING", 0),
    DIAMOND_LEGGINGS("DIAMOND_LEGGINGS", 0),
    DIAMOND_ORE("DIAMOND_ORE", 0),
    DIAMOND_PICKAXE("DIAMOND_PICKAXE", 0),
    DIAMOND_SHOVEL("DIAMOND_SPADE", 0),
    DIAMOND_SWORD("DIAMOND_SWORD", 0),
    DIORITE("STONE", 3),
    DIRT("DIRT", 0),
    DISPENSER("DISPENSER", 0),
    DOLPHIN_SPAWN_EGG("MONSTER_EGG", 0),
    DONKEY_SPAWN_EGG("MONSTER_EGG", 0),
    DRAGON_BREATH("DRAGONS_BREATH", 0),
    DRAGON_EGG("DRAGON_EGG", 0),
    DRAGON_HEAD(5, "SKULL", "SKULL_ITEM"),
    DRAGON_WALL_HEAD("SKULL", 5),
    DRIED_KELP("STONE", 0),
    DRIED_KELP_BLOCK("STONE", 0),
    DROPPER("DROPPER", 0),
    DROWNED_SPAWN_EGG("MONSTER_EGG", 0),
    EGG("EGG", 0),
    ELDER_GUARDIAN_SPAWN_EGG("MONSTER_EGG", 0),
    ELYTRA("ELYTRA", 0),
    EMERALD("EMERALD", 0),
    EMERALD_BLOCK("EMERALD_BLOCK", 0),
    EMERALD_ORE("EMERALD_ORE", 0),
    ENCHANTED_BOOK("ENCHANTED_BOOK", 0),
    ENCHANTED_GOLDEN_APPLE("GOLDEN_APPLE", 1),
    ENCHANTING_TABLE("ENCHANTMENT_TABLE", 0),
    ENDERMAN_SPAWN_EGG("MONSTER_EGG", 0),
    ENDERMITE_SPAWN_EGG("MONSTER_EGG", 0),
    ENDER_CHEST("ENDER_CHEST", 0),
    ENDER_EYE("EYE_OF_ENDER", 0),
    ENDER_PEARL("ENDER_PEARL", 0),
    END_CRYSTAL("END_CRYSTAL", 0),
    END_GATEWAY("END_GATEWAY", 0),
    END_PORTAL("ENDER_PORTAL", 0),
    END_PORTAL_FRAME("ENDER_PORTAL_FRAME", 0),
    END_ROD("END_ROD", 0),
    END_STONE("ENDER_STONE", 0),
    END_STONE_BRICKS("END_BRICKS", 0),
    EVOKER_SPAWN_EGG("MONSTER_EGG", 0),
    EXPERIENCE_BOTTLE("EXP_BOTTLE", 0),
    FARMLAND("SOIL", 0),
    FEATHER("FEATHER", 0),
    FERMENTED_SPIDER_EYE("FERMENTED_SPIDER_EYE", 0),
    FERN("LONG_GRASS", 2),
    FILLED_MAP("MAP", 0),
    FIRE("FIRE", 0),
    FIREWORK_ROCKET("FIREWORK", 0),
    FIREWORK_STAR("FIREWORK_CHARGE", 0),
    FIRE_CHARGE("FIREBALL", 0),
    FIRE_CORAL("STONE", 0),
    FIRE_CORAL_BLOCK("STONE", 0),
    FIRE_CORAL_FAN("STONE", 0),
    FIRE_CORAL_WALL_FAN("STONE", 0),
    FISHING_ROD("FISHING_ROD", 0),
    FLINT("FLINT", 0),
    FLINT_AND_STEEL("FLINT_AND_STEEL", 0),
    FLOWER_POT(0, "FLOWER_POT", "FLOWER_POT_ITEM"),
    FROSTED_ICE("FROSTED_ICE", 0),
    FURNACE(0, "FURNACE", "BURNING_FURNACE"),
    FURNACE_MINECART("POWERED_MINECART", 0),
    GHAST_SPAWN_EGG("MONSTER_EGG", 0),
    GHAST_TEAR("GHAST_TEAR", 0),
    GLASS("GLASS", 0),
    GLASS_BOTTLE("GLASS_BOTTLE", 0),
    GLASS_PANE("THIN_GLASS", 0),
    GLISTERING_MELON_SLICE("SPECKLED_MELON", 0),
    GLOWSTONE("GLOWSTONE", 0),
    GLOWSTONE_DUST("GLOWSTONE_DUST", 0),
    GOLDEN_APPLE("GOLDEN_APPLE", 0),
    GOLDEN_AXE("GOLD_AXE", 0),
    GOLDEN_BOOTS("GOLD_BOOTS", 0),
    GOLDEN_CARROT("GOLDEN_CARROT", 0),
    GOLDEN_CHESTPLATE("GOLD_CHESTPLATE", 0),
    GOLDEN_HELMET("GOLD_HELMET", 0),
    GOLDEN_HOE("GOLD_HOE", 0),
    GOLDEN_HORSE_ARMOR("GOLD_BARDING", 0),
    GOLDEN_LEGGINGS("GOLD_LEGGINGS", 0),
    GOLDEN_PICKAXE("GOLD_PICKAXE", 0),
    GOLDEN_SHOVEL("GOLD_SPADE", 0),
    GOLDEN_SWORD("GOLD_SWORD", 0),
    GOLD_BLOCK("GOLD_BLOCK", 0),
    GOLD_INGOT("GOLD_INGOT", 0),
    GOLD_NUGGET("GOLD_NUGGET", 0),
    GOLD_ORE("GOLD_ORE", 0),
    GRANITE("STONE", 1),
    GRASS("GRASS", 0),
    GRASS_BLOCK("GRASS", 0),
    GRASS_PATH("GRASS_PATH", 0),
    GRAVEL("GRAVEL", 0),
    GRAY_BANNER(8, "BANNER", "STANDING_BANNER"),
    GRAY_BED("BED", 7),
    GRAY_CARPET("CARPET", 7),
    GRAY_CONCRETE("CONCRETE", 7),
    GRAY_CONCRETE_POWDER("CONCRETE_POWDER", 7),
    GRAY_DYE("INK_SACK", 8),
    GRAY_GLAZED_TERRACOTTA("GRAY_GLAZED_TERRACOTTA", 0),
    GRAY_SHULKER_BOX("GRAY_SHULKER_BOX", 0),
    GRAY_STAINED_GLASS("STAINED_GLASS", 7),
    GRAY_STAINED_GLASS_PANE("STAINED_GLASS_PANE", 7),
    GRAY_TERRACOTTA("STAINED_CLAY", 7),
    GRAY_WALL_BANNER("WALL_BANNER", 0),
    GRAY_WOOL("WOOL", 7),
    GREEN_BANNER(2, "BANNER", "STANDING_BANNER"),
    GREEN_BED("BED", 13),
    GREEN_CARPET("CARPET", 13),
    GREEN_CONCRETE("CONCRETE", 13),
    GREEN_CONCRETE_POWDER("CONCRETE_POWDER", 13),
    GREEN_GLAZED_TERRACOTTA("GREEN_GLAZED_TERRACOTTA", 0),
    GREEN_SHULKER_BOX("GREEN_SHULKER_BOX", 0),
    GREEN_STAINED_GLASS("STAINED_GLASS", 13),
    GREEN_STAINED_GLASS_PANE("STAINED_GLASS_PANE", 13),
    GREEN_TERRACOTTA("STAINED_CLAY", 13),
    GREEN_WALL_BANNER("WALL_BANNER", 0),
    GREEN_WOOL("WOOL", 13),
    GUARDIAN_SPAWN_EGG("MONSTER_EGG", 0),
    GUNPOWDER("SULPHUR", 0),
    HAY_BLOCK("HAY_BLOCK", 0),
    HEART_OF_THE_SEA("STONE", 0),
    HEAVY_WEIGHTED_PRESSURE_PLATE("IRON_PLATE", 0),
    HOPPER("HOPPER", 0),
    HOPPER_MINECART("HOPPER_MINECART", 0),
    HORN_CORAL("STONE", 0),
    HORN_CORAL_BLOCK("STONE", 0),
    HORN_CORAL_FAN("STONE", 0),
    HORN_CORAL_WALL_FAN("STONE", 0),
    HORSE_SPAWN_EGG("MONSTER_EGG", 0),
    HUSK_SPAWN_EGG("MONSTER_EGG", 0),
    ICE("ICE", 0),
    INFESTED_CHISELED_STONE_BRICKS("MONSTER_EGGS", 5),
    INFESTED_COBBLESTONE("MONSTER_EGGS", 1),
    INFESTED_CRACKED_STONE_BRICKS("MONSTER_EGGS", 4),
    INFESTED_MOSSY_STONE_BRICKS("MONSTER_EGGS", 3),
    INFESTED_STONE("MONSTER_EGGS", 0),
    INFESTED_STONE_BRICKS("MONSTER_EGGS", 2),
    INK_SAC("INK_SACK", 0),
    IRON_AXE("IRON_AXE", 0),
    IRON_BARS("IRON_FENCE", 0),
    IRON_BLOCK("IRON_BLOCK", 0),
    IRON_BOOTS("IRON_BOOTS", 0),
    IRON_CHESTPLATE("IRON_CHESTPLATE", 0),
    IRON_DOOR(0, "IRON_DOOR", "IRON_DOOR_BLOCK"),
    IRON_HELMET("IRON_HELMET", 0),
    IRON_HOE("IRON_HOE", 0),
    IRON_HORSE_ARMOR("IRON_BARDING", 0),
    IRON_INGOT("IRON_INGOT", 0),
    IRON_LEGGINGS("IRON_LEGGINGS", 0),
    IRON_NUGGET("IRON_NUGGET", 0),
    IRON_ORE("IRON_ORE", 0),
    IRON_PICKAXE("IRON_PICKAXE", 0),
    IRON_SHOVEL("IRON_SPADE", 0),
    IRON_SWORD("IRON_SWORD", 0),
    IRON_TRAPDOOR("IRON_TRAPDOOR", 0),
    ITEM_FRAME("ITEM_FRAME", 0),
    JACK_O_LANTERN("JACK_O_LANTERN", 0),
    JUKEBOX("JUKEBOX", 0),
    JUNGLE_BOAT("BOAT_JUNGLE", 0),
    JUNGLE_BUTTON("WOOD_BUTTON", 0),
    JUNGLE_DOOR(0, "JUNGLE_DOOR", "JUNGLE_DOOR_ITEM"),
    JUNGLE_FENCE("JUNGLE_FENCE", 0),
    JUNGLE_FENCE_GATE("JUNGLE_FENCE_GATE", 0),
    JUNGLE_LEAVES("LEAVES", 3),
    JUNGLE_LOG("LOG", 3),
    JUNGLE_PLANKS("WOOD", 3),
    JUNGLE_PRESSURE_PLATE("WOOD_PLATE", 0),
    JUNGLE_SAPLING("SAPLING", 3),
    JUNGLE_SLAB(3, "WOODEN_SLAB", "WOOD_STEP", "WOOD_DOUBLE_STEP"),
    JUNGLE_STAIRS("JUNGLE_WOOD_STAIRS", 0),
    JUNGLE_TRAPDOOR("TRAP_DOOR", 0),
    JUNGLE_WOOD("LOG", 3),
    KELP("STONE", 0),
    KELP_PLANT("STONE", 0),
    KNOWLEDGE_BOOK("KNOWLEDGE_BOOK", 0),
    LADDER("LADDER", 0),
    LAPIS_BLOCK("LAPIS_BLOCK", 0),
    LAPIS_LAZULI("INK_SACK", 4),
    LAPIS_ORE("LAPIS_ORE", 0),
    LARGE_FERN("DOUBLE_PLANT", 3),
    LAVA(0, "LAVA", "STATIONARY_LAVA"),
    LAVA_BUCKET("LAVA_BUCKET", 0),
    LEAD("LEASH", 0),
    LEATHER("LEATHER", 0),
    LEATHER_BOOTS("LEATHER_BOOTS", 0),
    LEATHER_CHESTPLATE("LEATHER_CHESTPLATE", 0),
    LEATHER_HELMET("LEATHER_HELMET", 0),
    LEATHER_LEGGINGS("LEATHER_LEGGINGS", 0),
    LEVER("LEVER", 0),
    LIGHT_BLUE_BANNER(12, "BANNER", "STANDING_BANNER"),
    LIGHT_BLUE_BED("BED", 3),
    LIGHT_BLUE_CARPET("CARPET", 3),
    LIGHT_BLUE_CONCRETE("CONCRETE", 3),
    LIGHT_BLUE_CONCRETE_POWDER("CONCRETE_POWDER", 3),
    LIGHT_BLUE_DYE("INK_SACK", 12),
    LIGHT_BLUE_GLAZED_TERRACOTTA("LIGHT_BLUE_GLAZED_TERRACOTTA", 0),
    LIGHT_BLUE_SHULKER_BOX("LIGHT_BLUE_SHULKER_BOX", 0),
    LIGHT_BLUE_STAINED_GLASS("STAINED_GLASS", 3),
    LIGHT_BLUE_STAINED_GLASS_PANE("STAINED_GLASS_PANE", 3),
    LIGHT_BLUE_TERRACOTTA("STAINED_CLAY", 3),
    LIGHT_BLUE_WALL_BANNER("BANNER", 0),
    LIGHT_BLUE_WOOL("WOOL", 3),
    LIGHT_GRAY_BANNER(7, "BANNER", "STANDING_BANNER"),
    LIGHT_GRAY_BED("BED", 8),
    LIGHT_GRAY_CARPET("CARPET", 8),
    LIGHT_GRAY_CONCRETE("CONCRETE", 8),
    LIGHT_GRAY_CONCRETE_POWDER("CONCRETE_POWDER", 8),
    LIGHT_GRAY_DYE("INK_SACK", 7),
    LIGHT_GRAY_GLAZED_TERRACOTTA("SILVER_GLAZED_TERRACOTTA", 0),
    LIGHT_GRAY_SHULKER_BOX("SILVER_SHULKER_BOX", 0),
    LIGHT_GRAY_STAINED_GLASS("STAINED_GLASS", 8),
    LIGHT_GRAY_STAINED_GLASS_PANE("STAINED_GLASS_PANE", 8),
    LIGHT_GRAY_TERRACOTTA("STAINED_CLAY", 8),
    LIGHT_GRAY_WALL_BANNER("WALL_BANNER", 0),
    LIGHT_GRAY_WOOL("WOOL", 8),
    LIGHT_WEIGHTED_PRESSURE_PLATE("GOLD_PLATE", 0),
    LILAC("DOUBLE_PLANT", 1),
    LILY_PAD("WATER_LILY", 0),
    LIME_BANNER(10, "BANNER", "STANDING_BANNER"),
    LIME_BED("BED", 5),
    LIME_CARPET("CARPET", 5),
    LIME_CONCRETE("CONCRETE", 5),
    LIME_CONCRETE_POWDER("CONCRETE_POWDER", 5),
    LIME_DYE("INK_SACK", 10),
    LIME_GLAZED_TERRACOTTA("LIME_GLAZED_TERRACOTTA", 0),
    LIME_SHULKER_BOX("LIME_SHULKER_BOX", 0),
    LIME_STAINED_GLASS("STAINED_GLASS", 5),
    LIME_STAINED_GLASS_PANE("STAINED_GLASS_PANE", 5),
    LIME_TERRACOTTA("STAINED_CLAY", 5),
    LIME_WALL_BANNER("WALL_BANNER", 0),
    LIME_WOOL("WOOL", 5),
    LINGERING_POTION("LINGERING_POTION", 0),
    LLAMA_SPAWN_EGG("MONSTER_EGG", 0),
    MAGENTA_BANNER(13, "BANNER", "STANDING_BANNER"),
    MAGENTA_BED("BED", 2),
    MAGENTA_CARPET("CARPET", 2),
    MAGENTA_CONCRETE("CONCRETE", 2),
    MAGENTA_CONCRETE_POWDER("CONCRETE_POWDER", 2),
    MAGENTA_DYE("INK_SACK", 13),
    MAGENTA_GLAZED_TERRACOTTA("MAGENTA_GLAZED_TERRACOTTA", 0),
    MAGENTA_SHULKER_BOX("MAGENTA_SHULKER_BOX", 0),
    MAGENTA_STAINED_GLASS("STAINED_GLASS", 2),
    MAGENTA_STAINED_GLASS_PANE("STAINED_GLASS_PANE", 2),
    MAGENTA_TERRACOTTA("STAINED_CLAY", 2),
    MAGENTA_WALL_BANNER("WALL_BANNER", 0),
    MAGENTA_WOOL("WOOL", 2),
    MAGMA_BLOCK("MAGMA", 0),
    MAGMA_CREAM("MAGMA_CREAM", 0),
    MAGMA_CUBE_SPAWN_EGG("MONSTER_EGG", 0),
    MAP(0, "MAP", "EMPTY_MAP"),
    MELON("MELON_BLOCK", 0),
    MELON_SEEDS("MELON_SEEDS", 0),
    MELON_SLICE("MELON", 0),
    MELON_STEM("MELON_STEM", 0),
    MILK_BUCKET("MILK_BUCKET", 0),
    MINECART("MINECART", 0),
    MOOSHROOM_SPAWN_EGG("MONSTER_EGG", 0),
    MOSSY_COBBLESTONE("MOSSY_COBBLESTONE", 0),
    MOSSY_COBBLESTONE_WALL("COBBLE_WALL", 1),
    MOSSY_STONE_BRICKS("SMOOTH_BRICK", 1),
    MOVING_PISTON("PISTON_MOVING_PIECE", 0),
    MULE_SPAWN_EGG("MONSTER_EGG", 0),
    MUSHROOM_STEM("HUGE_MUSHROOM_1", 0),
    MUSHROOM_STEW("MUSHROOM_SOUP", 0),
    MUSIC_DISC_11("GOLD_RECORD", 0),
    MUSIC_DISC_13("GREEN_RECORD", 0),
    MUSIC_DISC_BLOCKS("RECORD_3", 0),
    MUSIC_DISC_CAT("RECORD_4", 0),
    MUSIC_DISC_CHIRP("RECORD_5", 0),
    MUSIC_DISC_FAR("RECORD_6", 0),
    MUSIC_DISC_MALL("RECORD_7", 0),
    MUSIC_DISC_MELLOHI("RECORD_8", 0),
    MUSIC_DISC_STAL("RECORD_9", 0),
    MUSIC_DISC_STRAD("RECORD_10", 0),
    MUSIC_DISC_WAIT("RECORD_11", 0),
    MUSIC_DISC_WARD("RECORD_12", 0),
    MUTTON("MUTTON", 0),
    MYCELIUM("MYCEL", 0),
    NAME_TAG("NAME_TAG", 0),
    NAUTILUS_SHELL("STONE", 0),
    NETHERRACK("NETHERRACK", 0),
    NETHER_BRICK("NETHER_BRICK_ITEM", 0),
    NETHER_BRICKS("NETHER_BRICK", 0),
    NETHER_BRICK_FENCE("NETHER_FENCE", 0),
    NETHER_BRICK_SLAB(6, "STONE_SLAB", "STEP", "DOUBLE_STEP"),
    NETHER_BRICK_STAIRS("NETHER_BRICK_STAIRS", 0),
    NETHER_PORTAL("PORTAL", 0),
    NETHER_QUARTZ_ORE("QUARTZ_ORE", 0),
    NETHER_STAR("NETHER_STAR", 0),
    NETHER_WART("NETHER_STALK", 0),
    NETHER_WART_BLOCK(0, "NETHER_WART_BLOCK", "NETHER_WARTS"),
    NOTE_BLOCK("NOTE_BLOCK", 0),
    OAK_BOAT("BOAT", 0),
    OAK_BUTTON("WOOD_BUTTON", 0),
    OAK_DOOR(0, "WOODEN_DOOR", "WOOD_DOOR"),
    OAK_FENCE("FENCE", 0),
    OAK_FENCE_GATE("FENCE_GATE", 0),
    OAK_LEAVES("LEAVES", 0),
    OAK_LOG("LOG", 0),
    OAK_PLANKS("WOOD", 0),
    OAK_PRESSURE_PLATE("WOOD_PLATE", 0),
    OAK_SAPLING("SAPLING", 0),
    OAK_SLAB(0, "WOODEN_SLAB", "WOOD_STEP", "WOOD_DOUBLE_STEP"),
    OAK_STAIRS("WOOD_STAIRS", 0),
    OAK_TRAPDOOR("TRAP_DOOR", 0),
    OAK_WOOD("LOG", 0),
    OBSERVER("OBSERVER", 0),
    OBSIDIAN("OBSIDIAN", 0),
    OCELOT_SPAWN_EGG("RECORD_12", 0),
    ORANGE_BANNER(14, "BANNER", "STANDING_BANNER"),
    ORANGE_BED("BED", 1),
    ORANGE_CARPET("CARPET", 1),
    ORANGE_CONCRETE("CONCRETE", 1),
    ORANGE_CONCRETE_POWDER("CONCRETE_POWDER", 1),
    ORANGE_DYE("INK_SACK", 14),
    ORANGE_GLAZED_TERRACOTTA("ORANGE_GLAZED_TERRACOTTA", 0),
    ORANGE_SHULKER_BOX("ORANGE_SHULKER_BOX", 0),
    ORANGE_STAINED_GLASS("STAINED_GLASS", 1),
    ORANGE_STAINED_GLASS_PANE("STAINED_GLASS_PANE", 1),
    ORANGE_TERRACOTTA("STAINED_CLAY", 1),
    ORANGE_TULIP("RED_ROSE", 5),
    ORANGE_WALL_BANNER("WALL_BANNER", 0),
    ORANGE_WOOL("WOOL", 1),
    OXEYE_DAISY("RED_ROSE", 8),
    PACKED_ICE("PACKED_ICE", 0),
    PAINTING("PAINTING", 0),
    PAPER("PAPER", 0),
    PARROT_SPAWN_EGG("MONSTER_EGG", 0),
    PEONY("DOUBLE_PLANT", 5),
    PETRIFIED_OAK_SLAB("STONE", 0),
    PHANTOM_MEMBRANE("STONE", 0),
    PHANTOM_SPAWN_EGG("MONSTER_EGG", 0),
    PIG_SPAWN_EGG("MONSTER_EGG", 0),
    PINK_BANNER(9, "BANNER", "STANDING_BANNER"),
    PINK_BED("BED", 6),
    PINK_CARPET("CARPET", 6),
    PINK_CONCRETE("CONCRETE", 6),
    PINK_CONCRETE_POWDER("CONCRETE_POWDER", 6),
    PINK_DYE("INK_SACK", 9),
    PINK_GLAZED_TERRACOTTA("PINK_GLAZED_TERRACOTTA", 0),
    PINK_SHULKER_BOX("PINK_SHULKER_BOX", 0),
    PINK_STAINED_GLASS("STAINED_GLASS", 6),
    PINK_STAINED_GLASS_PANE("STAINED_GLASS_PANE", 6),
    PINK_TERRACOTTA("STAINED_CLAY", 6),
    PINK_TULIP("RED_ROSE", 7),
    PINK_WALL_BANNER("WALL_BANNER", 0),
    PINK_WOOL("WOOL", 6),
    PISTON("PISTON_BASE", 0),
    PISTON_HEAD("PISTON_EXTENSION", 0),
    PLAYER_HEAD(3, "SKULL", "SKULL_ITEM"),
    PLAYER_WALL_HEAD("SKULL", 3),
    PODZOL("DIRT", 2),
    POISONOUS_POTATO("POISONOUS_POTATO", 0),
    POLAR_BEAR_SPAWN_EGG("MONSTER_EGG", 0),
    POLISHED_ANDESITE("STONE", 6),
    POLISHED_DIORITE("STONE", 4),
    POLISHED_GRANITE("STONE", 2),
    POPPED_CHORUS_FRUIT("CHORUS_FRUIT_POPPED", 0),
    POPPY("RED_ROSE", 0),
    PORKCHOP("PORK", 0),
    POTATO("POTATO_ITEM", 0),
    POTATOES("POTATO", 0),
    POTION("POTION", 0),
    POTTED_ACACIA_SAPLING("FLOWER_POT", 0),
    POTTED_ALLIUM("FLOWER_POT", 0),
    POTTED_AZURE_BLUET("FLOWER_POT", 0),
    POTTED_BIRCH_SAPLING("FLOWER_POT", 0),
    POTTED_BLUE_ORCHID("FLOWER_POT", 0),
    POTTED_BROWN_MUSHROOM("FLOWER_POT", 0),
    POTTED_CACTUS("FLOWER_POT", 0),
    POTTED_DANDELION("FLOWER_POT", 0),
    POTTED_DARK_OAK_SAPLING("FLOWER_POT", 0),
    POTTED_DEAD_BUSH("FLOWER_POT", 0),
    POTTED_FERN("FLOWER_POT", 0),
    POTTED_JUNGLE_SAPLING("FLOWER_POT", 0),
    POTTED_OAK_SAPLING("FLOWER_POT", 0),
    POTTED_ORANGE_TULIP("FLOWER_POT", 0),
    POTTED_OXEYE_DAISY("FLOWER_POT", 0),
    POTTED_PINK_TULIP("FLOWER_POT", 0),
    POTTED_POPPY("FLOWER_POT", 0),
    POTTED_RED_MUSHROOM("FLOWER_POT", 0),
    POTTED_RED_TULIP("FLOWER_POT", 0),
    POTTED_SPRUCE_SAPLING("FLOWER_POT", 0),
    POTTED_WHITE_TULIP("FLOWER_POT", 0),
    POWERED_RAIL("POWERED_RAIL", 0),
    PRISMARINE("PRISMARINE", 0),
    PRISMARINE_BRICKS("PRISMARINE", 1),
    PRISMARINE_BRICK_SLAB("STONE", 0),
    PRISMARINE_BRICK_STAIRS("STONE", 0),
    PRISMARINE_CRYSTALS("PRISMARINE_CRYSTALS", 0),
    PRISMARINE_SHARD("PRISMARINE_SHARD", 0),
    PRISMARINE_SLAB("STONE", 0),
    PRISMARINE_STAIRS("STONE", 0),
    PUFFERFISH("RAW_FISH", 3),
    PUFFERFISH_BUCKET("STONE", 0),
    PUFFERFISH_SPAWN_EGG("MONSTER_EGG", 0),
    PUMPKIN("PUMPKIN", 0),
    PUMPKIN_PIE("PUMPKIN_PIE", 0),
    PUMPKIN_SEEDS("PUMPKIN_SEEDS", 0),
    PUMPKIN_STEM("PUMPKIN_STEM", 0),
    PURPLE_BANNER(5, "BANNER", "STANDING_BANNER"),
    PURPLE_BED("BED", 10),
    PURPLE_CARPET("CARPET", 10),
    PURPLE_CONCRETE("CONCRETE", 10),
    PURPLE_CONCRETE_POWDER("CONCRETE_POWDER", 10),
    PURPLE_DYE("INK_SACK", 5),
    PURPLE_GLAZED_TERRACOTTA("PURPLE_GLAZED_TERRACOTTA", 0),
    PURPLE_SHULKER_BOX("PURPLE_SHULKER_BOX", 0),
    PURPLE_STAINED_GLASS("STAINED_GLASS", 10),
    PURPLE_STAINED_GLASS_PANE("STAINED_GLASS_PANE", 10),
    PURPLE_TERRACOTTA("STAINED_CLAY", 10),
    PURPLE_WALL_BANNER("WALL_BANNER", 0),
    PURPLE_WOOL("WOOL", 10),
    PURPUR_BLOCK("PURPUR_BLOCK", 0),
    PURPUR_PILLAR("PURPUR_PILLAR", 0),
    PURPUR_SLAB(0, "PURPUR_SLAB", "PURPUR_DOUBLE_SLAB"),
    PURPUR_STAIRS("PURPUR_STAIRS", 0),
    QUARTZ("QUARTZ", 0),
    QUARTZ_BLOCK("QUARTZ_BLOCK", 0),
    QUARTZ_PILLAR("QUARTZ_BLOCK", 2),
    QUARTZ_SLAB(7, "STONE_SLAB", "STEP", "DOUBLE_STEP"),
    QUARTZ_STAIRS("QUARTZ_STAIRS", 0),
    RABBIT("RABBIT", 0),
    RABBIT_FOOT("RABBIT_FOOT", 0),
    RABBIT_HIDE("RABBIT_HIDE", 0),
    RABBIT_SPAWN_EGG("MONSTER_EGG", 0),
    RABBIT_STEW("RABBIT_STEW", 0),
    RAIL("RAILS", 0),
    REDSTONE("REDSTONE", 0),
    REDSTONE_BLOCK("REDSTONE_BLOCK", 0),
    REDSTONE_LAMP(0, "REDSTONE_LAMP_ON", "REDSTONE_LAMP_OFF"),
    REDSTONE_ORE(0, "REDSTONE_ORE", "GLOWING_REDSTONE_ORE"),
    REDSTONE_TORCH(0, "REDSTONE_TORCH_ON", "REDSTONE_TORCH_OFF"),
    REDSTONE_WALL_TORCH(1, "REDSTONE_TORCH_ON", "REDSTONE_TORCH_OFF"),
    REDSTONE_WIRE("REDSTONE_WIRE", 0),
    RED_BANNER(1, "BANNER", "STANDING_BANNER"),
    RED_BED(14, "BED", "BED_BLOCK"),
    RED_CARPET("CARPET", 14),
    RED_CONCRETE("CONCRETE", 14),
    RED_CONCRETE_POWDER("CONCRETE_POWDER", 14),
    RED_GLAZED_TERRACOTTA("RED_GLAZED_TERRACOTTA", 0),
    RED_MUSHROOM("RED_MUSHROOM", 0),
    RED_MUSHROOM_BLOCK(0, "RED_MUSHROOM", "HUGE_MUSHROOM_2"),
    RED_NETHER_BRICKS("RED_NETHER_BRICK", 0),
    RED_SAND("SAND", 1),
    RED_SANDSTONE("RED_SANDSTONE", 0),
    RED_SANDSTONE_SLAB(0, "STONE_SLAB2", "DOUBLE_STONE_SLAB2"),
    RED_SANDSTONE_STAIRS("RED_SANDSTONE_STAIRS", 0),
    RED_SHULKER_BOX("RED_SHULKER_BOX", 0),
    RED_STAINED_GLASS("STAINED_GLASS", 14),
    RED_STAINED_GLASS_PANE("STAINED_GLASS_PANE", 14),
    RED_TERRACOTTA("STAINED_CLAY", 14),
    RED_TULIP("RED_ROSE", 4),
    RED_WALL_BANNER("WALL_BANNER", 0),
    RED_WOOL("WOOL", 14),
    REPEATER(0, "DIODE", "DIODE_BLOCK_ON", "DIODE_BLOCK_OFF"),
    REPEATING_COMMAND_BLOCK("COMMAND_REPEATING", 0),
    ROSE_BUSH("DOUBLE_PLANT", 4),
    ROSE_RED("INK_SACK", 1),
    ROTTEN_FLESH("ROTTEN_FLESH", 0),
    SADDLE("SADDLE", 0),
    SALMON("RAW_FISH", 1),
    SALMON_BUCKET("BUCKET", 0),
    SALMON_SPAWN_EGG("MONSTER_EGG", 0),
    SAND("SAND", 0),
    SANDSTONE("SANDSTONE", 0),
    SANDSTONE_SLAB(1, "STONE_SLAB", "STEP", "DOUBLE_STEP"),
    SANDSTONE_STAIRS("SANDSTONE_STAIRS", 0),
    SCUTE("STONE", 0),
    SEAGRASS("STONE", 0),
    SEA_LANTERN("SEA_LANTERN", 0),
    SEA_PICKLE("STONE", 0),
    SHEARS("SHEARS", 0),
    SHEEP_SPAWN_EGG("MONSTER_EGG", 0),
    SHIELD("SHIELD", 0),
    SHULKER_BOX("PURPLE_SHULKER_BOX", 0),
    SHULKER_SHELL("SHULKER_SHELL", 0),
    SHULKER_SPAWN_EGG("MONSTER_EGG", 0),
    SILVERFISH_SPAWN_EGG("MONSTER_EGG", 0),
    SKELETON_HORSE_SPAWN_EGG("MONSTER_EGG", 0),
    SKELETON_SKULL(0, "SKULL", "SKULL_ITEM"),
    SKELETON_SPAWN_EGG("MONSTER_EGG", 0),
    SKELETON_WALL_SKULL("SKULL", 0),
    SLIME_BALL("SLIME_BALL", 0),
    SLIME_BLOCK("SLIME_BLOCK", 0),
    SLIME_SPAWN_EGG("MONSTER_EGG", 0),
    SMOOTH_QUARTZ("STONE", 0),
    SMOOTH_RED_SANDSTONE("RED_SANDSTONE", 2),
    SMOOTH_SANDSTONE("SANDSTONE", 2),
    SMOOTH_STONE("STONE", 0),
    SNOW("SNOW", 0),
    SNOWBALL("SNOW_BALL", 0),
    SNOW_BLOCK("SNOW_BLOCK", 0),
    SOUL_SAND("SOUL_SAND", 0),
    SPAWNER("MOB_SPAWNER", 0),
    SPECTRAL_ARROW("SPECTRAL_ARROW", 0),
    SPIDER_EYE("SPIDER_EYE", 0),
    SPIDER_SPAWN_EGG("MONSTER_EGG", 0),
    SPLASH_POTION("SPLASH_POTION", 0),
    SPONGE("SPONGE", 0),
    SPRUCE_BOAT("BOAT_SPRUCE", 0),
    SPRUCE_BUTTON("WOOD_BUTTON", 0),
    SPRUCE_DOOR(0, "SPRUCE_DOOR", "SPRUCE_DOOR_ITEM"),
    SPRUCE_FENCE("SPRUCE_FENCE", 0),
    SPRUCE_FENCE_GATE("SPRUCE_FENCE_GATE", 0),
    SPRUCE_LEAVES("LEAVES", 1),
    SPRUCE_LOG("LOG", 1),
    SPRUCE_PLANKS("WOOD", 1),
    SPRUCE_PRESSURE_PLATE("WOOD_PLATE", 0),
    SPRUCE_SAPLING("SAPLING", 1),
    SPRUCE_SLAB(1, "WOODEN_SLAB", "WOOD_STEP", "WOOD_DOUBLE_STEP"),
    SPRUCE_STAIRS("SPRUCE_WOOD_STAIRS", 0),
    SPRUCE_TRAPDOOR("TRAP_DOOR", 0),
    SPRUCE_WOOD("LOG", 1),
    SQUID_SPAWN_EGG("MONSTER_EGG", 0),
    STICK("STICK", 0),
    STICKY_PISTON("PISTON_STICKY_BASE", 0),
    STONE("STONE", 0),
    STONE_AXE("STONE_AXE", 0),
    STONE_BRICKS("SMOOTH_BRICK", 0),
    STONE_BRICK_SLAB(5, "STONE_SLAB", "STEP", "DOUBLE_STEP"),
    STONE_BRICK_STAIRS("SMOOTH_STAIRS", 0),
    STONE_BUTTON("STONE_BUTTON", 0),
    STONE_HOE("STONE_HOE", 0),
    STONE_PICKAXE("STONE_PICKAXE", 0),
    STONE_PRESSURE_PLATE("STONE_PLATE", 0),
    STONE_SHOVEL("STONE_SPADE", 0),
    STONE_SWORD("STONE_SWORD", 0),
    STRAY_SPAWN_EGG("MONSTER_EGG", 0),
    STRING("STRING", 0),
    STRIPPED_ACACIA_LOG("STONE", 0),
    STRIPPED_ACACIA_WOOD("STONE", 0),
    STRIPPED_BIRCH_LOG("STONE", 0),
    STRIPPED_BIRCH_WOOD("STONE", 0),
    STRIPPED_DARK_OAK_LOG("STONE", 0),
    STRIPPED_DARK_OAK_WOOD("STONE", 0),
    STRIPPED_JUNGLE_LOG("STONE", 0),
    STRIPPED_JUNGLE_WOOD("STONE", 0),
    STRIPPED_OAK_LOG("STONE", 0),
    STRIPPED_OAK_WOOD("STONE", 0),
    STRIPPED_SPRUCE_LOG("STONE", 0),
    STRIPPED_SPRUCE_WOOD("STONE", 0),
    STRUCTURE_BLOCK("STRUCTURE_BLOCK", 0),
    STRUCTURE_VOID("STRUCTURE_VOID", 0),
    SUGAR("SUGAR", 0),
    SUGAR_CANE(0, "SUGAR_CANE", "SUGAR_CANE_BLOCK"),
    SUNFLOWER("DOUBLE_PLANT", 0),
    TALL_GRASS("DOUBLE_PLANT", 2),
    TALL_SEAGRASS("STONE", 0),
    TERRACOTTA("HARD_CLAY", 0),
    TIPPED_ARROW("TIPPED_ARROW", 0),
    TNT("TNT", 0),
    TNT_MINECART("EXPLOSIVE_MINECART", 0),
    TORCH("TORCH", 0),
    TOTEM_OF_UNDYING("TOTEM", 0),
    TRAPPED_CHEST("TRAPPED_CHEST", 0),
    TRIDENT("STONE", 0),
    TRIPWIRE("TRIPWIRE", 0),
    TRIPWIRE_HOOK("TRIPWIRE_HOOK", 0),
    TROPICAL_FISH("RAW_FISH", 2),
    TROPICAL_FISH_BUCKET("BUCKET", 0),
    TROPICAL_FISH_SPAWN_EGG("MONSTER_EGG", 0),
    TUBE_CORAL("STONE", 0),
    TUBE_CORAL_BLOCK("STONE", 0),
    TUBE_CORAL_FAN("STONE", 0),
    TUBE_CORAL_WALL_FAN("STONE", 0),
    TURTLE_EGG("MONSTER_EGG", 0),
    TURTLE_HELMET("STONE", 0),
    TURTLE_SPAWN_EGG("MONSTER_EGG", 0),
    VEX_SPAWN_EGG("MONSTER_EGG", 0),
    VILLAGER_SPAWN_EGG("MONSTER_EGG", 0),
    VINDICATOR_SPAWN_EGG("MONSTER_EGG", 0),
    VINE("VINE", 0),
    VOID_AIR("AIR", 0),
    WALL_TORCH("TORCH", 1),
    WATER(0, "WATER", "STATIONARY_WATER"),
    WATER_BUCKET("WATER_BUCKET", 0),
    WET_SPONGE("SPONGE", 1),
    WHEAT(0, "WHEAT", "CROPS"),
    WHEAT_SEEDS(0, "WHEAT_SEEDS", "SEEDS"),
    WHITE_BANNER(15, "BANNER", "STANDING_BANNER"),
    WHITE_BED("BED", 0),
    WHITE_CARPET("CARPET", 0),
    WHITE_CONCRETE("CONCRETE", 0),
    WHITE_CONCRETE_POWDER("CONCRETE_POWDER", 0),
    WHITE_GLAZED_TERRACOTTA("WHITE_GLAZED_TERRACOTTA", 0),
    WHITE_SHULKER_BOX("WHITE_SHULKER_BOX", 0),
    WHITE_STAINED_GLASS("STAINED_GLASS", 0),
    WHITE_STAINED_GLASS_PANE("STAINED_GLASS_PANE", 0),
    WHITE_TERRACOTTA("TERRACOTTA", 0),
    WHITE_TULIP("RED_ROSE", 6),
    WHITE_WALL_BANNER("WALL_BANNER", 0),
    WHITE_WOOL("WOOL", 0),
    WITCH_SPAWN_EGG("MONSTER_EGG", 0),
    WITHER_SKELETON_SKULL(1, "SKULL", "SKULL_ITEM"),
    WITHER_SKELETON_SPAWN_EGG("MONSTER_EGG", 0),
    WITHER_SKELETON_WALL_SKULL("SKULL", 1),
    WOLF_SPAWN_EGG("MONSTER_EGG", 0),
    WOODEN_AXE("WOOD_AXE", 0),
    WOODEN_HOE("WOOD_HOE", 0),
    WOODEN_PICKAXE("WOOD_PICKAXE", 0),
    WOODEN_SHOVEL("WOOD_SPADE", 0),
    WOODEN_SWORD("WOOD_SWORD", 0),
    WRITABLE_BOOK("BOOK_AND_QUILL", 0),
    WRITTEN_BOOK("WRITTEN_BOOK", 0),
    YELLOW_BANNER(11, "BANNER", "STANDING_BANNER"),
    YELLOW_BED("BED", 4),
    YELLOW_CARPET("CARPET", 4),
    YELLOW_CONCRETE("CONCRETE", 4),
    YELLOW_CONCRETE_POWDER("CONCRETE_POWDER", 4),
    YELLOW_GLAZED_TERRACOTTA("YELLOW_GLAZED_TERRACOTTA", 0),
    YELLOW_SHULKER_BOX("YELLOW_SHULKER_BOX", 0),
    YELLOW_STAINED_GLASS("STAINED_GLASS", 4),
    YELLOW_STAINED_GLASS_PANE("STAINED_GLASS_PANE", 4),
    YELLOW_TERRACOTTA("STAINED_CLAY", 4),
    YELLOW_WALL_BANNER("WALL_BANNER", 0),
    YELLOW_WOOL("WOOL", 4),
    ZOMBIE_HEAD(2, "SKULL", "SKULL_ITEM"),
    ZOMBIE_HORSE_SPAWN_EGG("MONSTER_EGG", 0),
    ZOMBIE_PIGMAN_SPAWN_EGG("MONSTER_EGG", 0),
    ZOMBIE_SPAWN_EGG("MONSTER_EGG", 0),
    ZOMBIE_VILLAGER_SPAWN_EGG("MONSTER_EGG", 0),
    ZOMBIE_WALL_HEAD("SKULL", 2),

    //</editor-fold>

    // TODO Minecraft 1.14
    // Warning: Not yet released, just based on the draft of the wiki.
    // Link: https://minecraft.gamepedia.com/1.14

    @Draft @Deprecated("Draft") BAMBOO("STONE", 0),
    @Draft @Deprecated("Draft") BARREL("STONE", 0),
    @Draft @Deprecated("Draft") BELL("STONE", 0),
    @Draft @Deprecated("Draft") BLAST_FURNACE("STONE", 0),
    @Draft @Deprecated("Draft") CAMPFIRE("STONE", 0),
    @Draft @Deprecated("Draft") CARTOGRAPHY_TABLE("STONE", 0),
    @Draft @Deprecated("Draft") COMPOSTER("STONE", 0),
    @Draft @Deprecated("Draft") FLETCHING_TABLE("STONE", 0),
    @Draft @Deprecated("Draft") SMITHING_TABLE("STONE", 0),
    @Draft @Deprecated("Draft") STONECUTTER("STONE", 0),
    @Draft @Deprecated("Draft") CORNFLOWER("STONE", 0),
    @Draft @Deprecated("Draft") LILY_OF_THE_VALLEY("STONE", 0),
    @Draft @Deprecated("Draft") WITHER_ROSE("STONE", 0),
    @Draft @Deprecated("Draft") GRINDSTONE("STONE", 0),
    @Draft @Deprecated("Draft") JIGSAW("STONE", 0),
    @Draft @Deprecated("Draft") LANTERN("STONE", 0),
    @Draft @Deprecated("Draft") LECTERN("STONE", 0),
    @Draft @Deprecated("Draft") LOOM("STONE", 0),
    @Draft @Deprecated("Draft") SCAFFOLDING("STONE", 0),
    @Draft @Deprecated("Draft") SMOKER("STONE", 0),
    @Draft @Deprecated("Draft") SWEET_BERRY_BUSH("STONE", 0),

    @Draft @Deprecated("Draft") FLOWER_BANNER_PATTERN("PAPER", 0),
    @Draft @Deprecated("Draft") CREEPER_BANNER_PATTERN("PAPER", 0),
    @Draft @Deprecated("Draft") SKULL_BANNER_PATTERN("PAPER", 0),
    @Draft @Deprecated("Draft") MOJANG_BANNER_PATTERN("PAPER", 0),
    @Draft @Deprecated("Draft") GLOBE_BANNER_PATTERN("PAPER", 0), // since 19w11a
    @Draft @Deprecated("Draft") CROSSBOW("BOW", 0),
    @Draft @Deprecated("Draft") SUSPICIOUS_STEW("STONE", 0),
    @Draft @Deprecated("Draft") SWEET_BERRIES("STONE", 0),

    SIGN(0, "OAK_SIGN", "SIGN"), // TODO Need to test
    WALL_SIGN(0, "OAK_WALL_SIGN", "WALL_SIGN", "SIGN_POST"),
    @Draft @Deprecated("Draft") OAK_SIGN("SIGN", 0),
    @Draft @Deprecated("Draft") OAK_WALL_SIGN("WALL_SIGN", 0),
    @Draft @Deprecated("Draft") BIRCH_SIGN("SIGN", 0),
    @Draft @Deprecated("Draft") BIRCH_WALL_SIGN("WALL_SIGN", 0),
    @Draft @Deprecated("Draft") JUNGLE_SIGN("SIGN", 0),
    @Draft @Deprecated("Draft") JUNGEL_WALL_SIGN("WALL_SIGN", 0),
    @Draft @Deprecated("Draft") ACACIA_SIGN("SIGN", 0),
    @Draft @Deprecated("Draft") ACACIA_WALL_SIGN("WALL_SIGN", 0),
    @Draft @Deprecated("Draft") DARK_OAK_SIGN("SIGN", 0),
    @Draft @Deprecated("Draft") DARK_OAK_WALL_SIGN("WALL_SIGN", 0),
    @Draft @Deprecated("Draft") SPRUCE_SIGN("SIGN", 0),
    @Draft @Deprecated("Draft") SPRUCE_WALL_SIGN("WALL_SIGN", 0),

    @Draft @Deprecated("Draft") BLUE_DYE("STONE", 0),
    @Draft @Deprecated("Draft") BROWN_DYE("STONE", 0),
    @Draft @Deprecated("Draft") BLACK_DYE("STONE", 0),
    @Draft @Deprecated("Draft") WHITE_DYE("STONE", 0),

    @Draft @Deprecated("Draft") CAT_SPAWN_EGG("MONSTER_EGG", 0),
    @Draft @Deprecated("Draft") ILLAGER_BEAST_SPAWN_EGG("MONSTER_EGG", 0),
    @Draft @Deprecated("Draft") PANDA_SPAWN_EGG("MONSTER_EGG", 0),
    @Draft @Deprecated("Draft") PILLAGER_SPAWN_EGG("MONSTER_EGG", 0),

    @Draft @Deprecated("Draft") LEATHER_HORSE_ARMOR("STONE", 0),

    // TODO: Before 1.13: Smooth stone slab, After 1.14: Stone slab. Why did do this? Need to test
    STONE_SLAB(0, "STONE_SLAB", "STEP", "DOUBLE_STEP"),
    @Draft @Deprecated("Draft") ANDESITE_SLAB("STONE", 0),
    @Draft @Deprecated("Draft") POLISHED_ANDESITE_SLAB("STONE", 0),
    @Draft @Deprecated("Draft") DIORITE_SLAB("STONE", 0),
    @Draft @Deprecated("Draft") POLISHED_DIORITE_SLAB("STONE", 0),
    @Draft @Deprecated("Draft") GRANITE_SLAB("STONE", 0),
    @Draft @Deprecated("Draft") POLISHED_GRANITE_SLAB("STONE", 0),
    @Draft @Deprecated("Draft") MOSSY_STONE_BRICK_SLAB("STONE", 0),
    @Draft @Deprecated("Draft") MOSSY_COBBLESTONE_SLAB("STONE", 0),
    @Draft @Deprecated("Draft") SMOOTH_SANDSTONE_SLAB("STONE", 0),
    @Draft @Deprecated("Draft") SMOOTH_RED_SANDSTONE_SLAB("STONE", 0),
    @Draft @Deprecated("Draft") SMOOTH_QUARTZ_SLAB("STONE", 0),
    @Draft @Deprecated("Draft") RED_NETHER_BRICK_SLAB("STONE", 0),
    @Draft @Deprecated("Draft") END_STONE_BRICK_SLAB("STONE", 0),

    @Draft @Deprecated("Draft") STONE_STAIRS("STONE", 0),
    @Draft @Deprecated("Draft") ANDESITE_STAIRS("STONE", 0),
    @Draft @Deprecated("Draft") POLISHED_ANDESITE_STAIRS("STONE", 0),
    @Draft @Deprecated("Draft") DIORITE_STAIRS("STONE", 0),
    @Draft @Deprecated("Draft") POLISHED_DIORITE_STAIRS("STONE", 0),
    @Draft @Deprecated("Draft") GRANITE_STAIRS("STONE", 0),
    @Draft @Deprecated("Draft") POLISHED_GRANITE_STAIRS("STONE", 0),
    @Draft @Deprecated("Draft") MOSSY_STONE_BRICK_STAIRS("STONE", 0),
    @Draft @Deprecated("Draft") MOSSY_COBBLESTONE_STAIRS("STONE", 0),
    @Draft @Deprecated("Draft") SMOOTH_SANDSTONE_STAIRS("STONE", 0),
    @Draft @Deprecated("Draft") SMOOTH_RED_SANDSTONE_STAIRS("STONE", 0),
    @Draft @Deprecated("Draft") SMOOTH_QUARTZ_STAIRS("STONE", 0),
    @Draft @Deprecated("Draft") RED_NETHER_BRICK_STAIRS("STONE", 0),
    @Draft @Deprecated("Draft") END_STONE_BRICK_STAIRS("STONE", 0),

    @Draft @Deprecated("Draft") STONE_BRICK_WALL("STONE", 0),
    @Draft @Deprecated("Draft") ANDESITE_WALL("STONE", 0),
    @Draft @Deprecated("Draft") DIORITE_WALL("STONE", 0),
    @Draft @Deprecated("Draft") GRANITE_WALL("STONE", 0),
    @Draft @Deprecated("Draft") MOSSY_STONE_BRICK_WALL("STONE", 0),
    @Draft @Deprecated("Draft") SANDSTONE_WALL("STONE", 0),
    @Draft @Deprecated("Draft")  RED_SANDSTONE_WALL("STONE", 0),
    @Draft @Deprecated("Draft") RED_NETHER_BRICK_WALL("STONE", 0),
    @Draft @Deprecated("Draft") END_STONE_BRICK_WALL("STONE", 0),
    @Draft @Deprecated("Draft") PRISMARINE_WALL("STONE", 0),
    @Draft @Deprecated("Draft") BRICK_WALL("STONE", 0),
    @Draft @Deprecated("Draft") NETHER_BRICK_WALL("STONE", 0),

    @Draft @Deprecated("Draft") CUT_SANDSTONE_SLAB("STONE", 0), // since 19w12a
    @Draft @Deprecated("Draft") CUT_RED_SANDSTONE_SLAB("STONE", 0), // since 19w12a
    ;

    private val aliases : Array<out String>
    private val data : Int

    constructor(alias: String, data: Int) {
        this.aliases = arrayOf(alias)
        this.data = data
    }

    constructor(data: Int, vararg aliases: String) {
        this.aliases = aliases
        this.data = data
    }

    /**
     * * Convert this material compatible enum to Bukkit material.
     * * 将此材料兼容枚举转换为 Bukkit 的材料.
     *
     * @see [Material]
     * @throws [UnsupportedOperationException] If the material is not compatible.
     * @throws [UnsupportedOperationException] 如果材料不兼容.
     */
    @Throws(UnsupportedOperationException::class)
    fun toBukkit(): Material
            = toBukkit(this)

    /**
     * * Compare the given [itemStack] with this material for the same material type.
     * * 将给定的物品栈 [itemStack] 和此材料对比是否为相同的材料类型.
     *
     * @throws [UnsupportedOperationException] If the material is not compatible.
     * @throws [UnsupportedOperationException] 如果材料不兼容.
     */
    @Throws(UnsupportedOperationException::class)
    fun isSameType(itemStack: ItemStack): Boolean
            = isSameType(this, itemStack)

    /**
     * * Create this item stack object with the given [count].
     * * 将此材料用给定的数量 [count] 创建物品栈对象.
     *
     * @throws [UnsupportedOperationException] If the material is not compatible.
     * @throws [UnsupportedOperationException] 如果材料不兼容.
     */
    @JvmOverloads
    @Throws(UnsupportedOperationException::class)
    fun createStack(count: Int = 1): ItemStack
            = createStack(this, count)

//    SEE : ldk-bukkit-common / com.lgou2w.ldk.bukkit.item.ItemKt
//    // ItemBuilder Extended
//    @JvmOverloads
//    fun builder(count: Int = 1, durability: Int = 0, block: Applicator<ItemBuilder> = {}) : ItemBuilder
//            = toBukkit().builder(count, durability, block)

    companion object {

        /**
         * ### Before 1.13 <=> TYPE:DATA
         * Case: WOOL:15 -> BLACK_WOOL
         * Case: STONE:5 -> ANDESITE
         *
         * ### After 1.13
         * Case: RED_WOOL -> RED_WOOL
         */
        @JvmStatic
        private val LOOKUPS : MutableMap<String, XMaterial> = Collections.synchronizedMap(HashMap())

        /**
         * * Converts a given material compatible enumeration [xMaterial] to Bukkit material.
         * * 将给定的材料兼容枚举 [xMaterial] 转换为 Bukkit 的材料.
         *
         * @throws [UnsupportedOperationException] If the material is not compatible.
         * @throws [UnsupportedOperationException] 如果材料不兼容.
         */
        @JvmStatic
        @Throws(UnsupportedOperationException::class)
        fun toBukkit(xMaterial: XMaterial): Material {
            val value = Material.matchMaterial(xMaterial.name)
            return value ?: xMaterial.aliases.mapNotNull { Material.matchMaterial(it) }.firstOrNull()
                   ?: throw UnsupportedOperationException("Internal error, unsupported '$xMaterial' material type.")
        }

        /**
         * * Convert a given [material] to a material compatible enumeration.
         * * 将给定的材料 [material] 转换为材料兼容枚举.
         *
         * @throws [UnsupportedOperationException] If the material is not compatible.
         * @throws [UnsupportedOperationException] 如果材料不兼容.
         */
        @JvmStatic
        @Throws(UnsupportedOperationException::class)
        fun fromBukkit(material: Material): XMaterial {
            return searchByBukkit(material)
                   ?: throw UnsupportedOperationException("Internal error, unsupported '$material' material type.")
        }

        /**
         * * Search for material compatible enumerations from the given [material]. If found, return `null`.
         * * 从给定的材料 [material] 搜索材料兼容枚举. 如果为找到则返回 `null`.
         */
        @JvmStatic
        fun searchByBukkit(material: Material): XMaterial? {
            val type = material.name.toUpperCase(Locale.US)
            return try {
                XMaterial.valueOf(type)
            } catch (e: IllegalArgumentException) {
                searchByType(type)
            }
        }

         // Before 1.13 <=> `TYPE:DATA`, case: `WOOL:15` == `BLACK_WOOL`
         // After 1.13 <=> `TYPE`, case: `BLACK_WOOL`, `RED_BED`
        /**
         * * Search for material compatible enumerations from the given [type] name. If found, return `null`.
         * * 从给定的类型名称 [type] 搜索材料兼容枚举. 如果为找到则返回 `null`.
         */
        @JvmStatic
        fun searchByType(type: String): XMaterial? {
            val typeUpperCase = type.toUpperCase(Locale.US)
            val typeKey = typeUpperCase.split(":").getOrNull(0) ?: typeUpperCase
            val data = typeUpperCase.split(":").getOrNull(1)?.toIntOrNull() // TYPE:DATA
            val lookupKey = if (data != null) "$typeKey:$data" else typeKey
            val lookup = LOOKUPS[lookupKey]
            if (lookup != null) {
                return lookup
            } else {
                var matched : XMaterial?
                try {
                    matched = XMaterial.valueOf(typeKey)
                    val validate = matched.toBukkit()
                    if (matched.name != validate.name && !matched.aliases.any { it == validate.name })
                        matched = null
                } catch (e: Exception) {
                    matched = null
                }
                if (matched == null || (data != null && matched.data != data))
                    matched = XMaterial.values().find { it.aliases.contains(typeKey) && it.data == data ?: 0 }
                return if (matched != null) {
                    LOOKUPS[lookupKey] = matched
                    matched
                } else {
                    null
                }
            }
        }

        /**
         * * Compare the given [xMaterial] with the [itemStack] for the same material type.
         * * 将给定的材料 [xMaterial] 和物品栈 [itemStack] 对比是否为相同的材料类型.
         *
         * @throws [UnsupportedOperationException] If the material is not compatible.
         * @throws [UnsupportedOperationException] 如果材料不兼容.
         */
        @JvmStatic
        @Throws(UnsupportedOperationException::class)
        fun isSameType(xMaterial: XMaterial, itemStack: ItemStack): Boolean {
            val bukkit = toBukkit(xMaterial)
            val type = itemStack.type
            return if (MinecraftBukkitVersion.isV113OrLater) {
                bukkit == type
            } else {
                // Before version 1.13
                @Suppress("DEPRECATION")
                val data = itemStack.data.notNull().data.toInt()
                bukkit == type && xMaterial.data == data
            }
        }

        /**
         * * Creates the item stack object for the given [xMaterial] and the given [count].
         * * 将给定的材料 [xMaterial] 和给定的数量 [count] 创建物品栈对象.
         *
         * @throws [UnsupportedOperationException] If the material is not compatible.
         * @throws [UnsupportedOperationException] 如果材料不兼容.
         */
        @JvmStatic
        @JvmOverloads
        @Throws(UnsupportedOperationException::class)
        fun createStack(xMaterial: XMaterial, count: Int = 1): ItemStack {
            val type = toBukkit(xMaterial)
            return if (MinecraftBukkitVersion.isV113OrLater) {
                ItemStack(type, count)
            } else {
                // Before version 1.13
                @Suppress("DEPRECATION")
                ItemStack(type, count, xMaterial.data.toShort())
            }
        }

        @JvmStatic
        @Deprecated("DEBUG : Traverse all types from Bukkit to match.")
        fun runtimeTest() {
            var unsupportedCount = 0
            Bukkit.getLogger().warning("-------- * XMaterial Runtime Test * -----")
            Material.values().forEach { type ->
                val xMaterial = XMaterial.searchByBukkit(type)
                if (xMaterial == null) {
                    Bukkit.getLogger().warning("> Material.${type.name} = Unsupported")
                    unsupportedCount++
                }
            }
            if (unsupportedCount != 0) {
                Bukkit.getLogger().warning("A total of $unsupportedCount material types are not supported.")
                Bukkit.getLogger().warning("Contact https://github.com/lgou2w/ldk for updates.")
            } else
                Bukkit.getLogger().warning("No incompatible material types. ;)")
            Bukkit.getLogger().warning("-------------------------")
        }
    }
}

// See: https://github.com/lgou2w/ldk/issues/61
/**
 * @since LDK 0.1.8-rc
 */
typealias Materials = XMaterial

/**
 * @since LDK 0.1.8-rc
 */
infix fun XMaterial.eq(material: Material): Boolean
        = toBukkit() == material

/**
 * @since LDK 0.1.8-rc
 */
infix fun XMaterial.notEq(material: Material): Boolean
        = toBukkit() != material

/**
 * @since LDK 0.1.8-rc
 */
infix fun XMaterial.eq(stack: ItemStack): Boolean
        = isSameType(stack)

/**
 * @since LDK 0.1.8-rc
 */
infix fun XMaterial.notEq(stack: ItemStack): Boolean
        = !isSameType(stack)
/**
 * @since LDK 0.1.8-rc
 */
infix fun ItemStack.eq(xMaterial: XMaterial): Boolean
        = xMaterial.isSameType(this)

/**
 * @since LDK 0.1.8-rc
 */
infix fun ItemStack.notEq(xMaterial: XMaterial): Boolean
        = !xMaterial.isSameType(this)
